// # ResumeIQ Professional Resume Analysis Report


import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateReportPDF = (analysis) => {
  if (!analysis) return;

  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  // ---------- Helpers ----------

  const addHeader = (sectionTitle = "") => {
    doc.setFillColor(45, 55, 72);
    doc.rect(0, 0, pageWidth, 18, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(255, 255, 255);
    doc.text("ResumeIQ", margin, 12);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("AI Resume Analysis", pageWidth - margin, 12, {
      align: "right",
    });

    if (sectionTitle) {
      doc.setTextColor(45, 55, 72);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(18);
      doc.text(sectionTitle, margin, 32);
    }
  };

  const addFooter = (pageNumber) => {
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, pageHeight - 18, pageWidth - margin, pageHeight - 18);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(130, 130, 130);

    doc.text("Generated by ResumeIQ", margin, pageHeight - 10);

    doc.text(
      `Page ${pageNumber}`,
      pageWidth - margin,
      pageHeight - 10,
      { align: "right" }
    );
  };

  const addWrappedText = (
    text,
    x,
    y,
    maxWidth,
    lineHeight = 6,
    fontSize = 10
  ) => {
    doc.setFontSize(fontSize);

    const lines = doc.splitTextToSize(String(text), maxWidth);

    lines.forEach((line) => {
      doc.text(line, x, y);
      y += lineHeight;
    });

    return y;
  };

  const getScoreInfo = (score) => {
    if (score >= 80) {
      return {
        label: "Excellent",
        description:
          "Your resume is highly optimized for ATS screening.",
      };
    }

    if (score >= 60) {
      return {
        label: "Moderately Optimized",
        description:
          "Your resume has a good foundation but still has room for improvement.",
      };
    }

    if (score >= 40) {
      return {
        label: "Needs Improvement",
        description:
          "Several areas of your resume could reduce its ATS performance.",
      };
    }

    return {
      label: "Poor",
      description:
        "Your resume needs significant improvements for better ATS compatibility.",
    };
  };

  // =========================================================
  // PAGE 1 — COVER / ATS SCORE
  // =========================================================

  doc.setFillColor(248, 250, 252);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Top branding
  doc.setFillColor(45, 55, 72);
  doc.rect(0, 0, pageWidth, 24, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(255, 255, 255);
  doc.text("ResumeIQ", margin, 15);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("AI Resume Intelligence", pageWidth - margin, 15, {
    align: "right",
  });

  // Title
  doc.setTextColor(35, 45, 60);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(25);
  doc.text("Resume Analysis", pageWidth / 2, 55, {
    align: "center",
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(110, 120, 135);
  doc.text(
    "AI-powered evaluation of your resume",
    pageWidth / 2,
    64,
    { align: "center" }
  );

  // Score
  const score = Number(analysis.score) || 0;
  const scoreInfo = getScoreInfo(score);

  doc.setFillColor(255, 255, 255);
  doc.roundedRect(35, 82, 140, 78, 6, 6, "F");

  doc.setDrawColor(225, 230, 235);
  doc.roundedRect(35, 82, 140, 78, 6, 6);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(90, 100, 115);
  doc.text("ATS COMPATIBILITY SCORE", pageWidth / 2, 98, {
    align: "center",
  });

  doc.setFontSize(42);
  doc.setTextColor(45, 55, 72);
  doc.text(`${score}`, pageWidth / 2 - 7, 130, {
    align: "center",
  });

  doc.setFontSize(14);
  doc.setTextColor(120, 130, 145);
  doc.text("/ 100", pageWidth / 2 + 22, 130);

  // Score label
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(70, 80, 95);
  doc.text(scoreInfo.label, pageWidth / 2, 147, {
    align: "center",
  });

  // Progress bar
  const barX = 50;
  const barY = 171;
  const barWidth = 120;
  const barHeight = 7;

  doc.setFillColor(225, 230, 235);
  doc.roundedRect(barX, barY, barWidth, barHeight, 3, 3, "F");

  doc.setFillColor(75, 85, 105);
  doc.roundedRect(
    barX,
    barY,
    Math.min(score, 100) * 1.2,
    barHeight,
    3,
    3,
    "F"
  );

  // Interpretation
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(85, 95, 110);

  addWrappedText(
    scoreInfo.description,
    45,
    195,
    120,
    6,
    10
  );

  // Summary cards
  const cardY = 225;
  const cardWidth = 52;
  const gap = 7;

  const summaryCards = [
    {
      title: "Strengths",
      value: analysis.strengths?.length || 0,
    },
    {
      title: "Weaknesses",
      value: analysis.weaknesses?.length || 0,
    },
    {
      title: "Missing Keywords",
      value: analysis.missingKeywords?.length || 0,
    },
  ];

  summaryCards.forEach((card, index) => {
    const x = margin + index * (cardWidth + gap);

    doc.setFillColor(255, 255, 255);
    doc.roundedRect(x, cardY, cardWidth, 35, 4, 4, "F");

    doc.setDrawColor(225, 230, 235);
    doc.roundedRect(x, cardY, cardWidth, 35, 4, 4);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(17);
    doc.setTextColor(45, 55, 72);
    doc.text(String(card.value), x + cardWidth / 2, cardY + 17, {
      align: "center",
    });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(110, 120, 135);
    doc.text(card.title, x + cardWidth / 2, cardY + 27, {
      align: "center",
    });
  });

  // Cover footer
  doc.setFontSize(8);
  doc.setTextColor(140, 145, 155);
  doc.text(
    "ResumeIQ © 2026 • AI-generated resume assessment",
    pageWidth / 2,
    280,
    { align: "center" }
  );

  // =========================================================
  // PAGE 2 — STRENGTHS / WEAKNESSES / KEYWORDS
  // =========================================================

  doc.addPage();
  addHeader("Resume Insights");

  let y = 45;

  // Strengths
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(45, 55, 72);
  doc.text("01  Strengths", margin, y);

  y += 10;

  const strengths = analysis.strengths || [];

  strengths.forEach((item) => {
    // Check page space
    if (y > pageHeight - 35) {
      addFooter(2);
      doc.addPage();
      addHeader("Resume Insights");
      y = 45;
    }

    doc.setFillColor(240, 253, 244);
    doc.circle(margin + 2, y - 1.5, 2, "F");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(65, 75, 90);

    y = addWrappedText(
      item,
      margin + 8,
      y,
      pageWidth - margin * 2 - 8,
      6,
      10
    );

    y += 3;
  });

  // Weaknesses
  y += 5;

  if (y > pageHeight - 70) {
    addFooter(2);
    doc.addPage();
    addHeader("Resume Insights");
    y = 45;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(45, 55, 72);
  doc.text("02  Areas for Improvement", margin, y);

  y += 10;

  const weaknesses = analysis.weaknesses || [];

  weaknesses.forEach((item) => {
    if (y > pageHeight - 35) {
      addFooter(2);
      doc.addPage();
      addHeader("Resume Insights");
      y = 45;
    }

    doc.setFillColor(254, 242, 242);
    doc.circle(margin + 2, y - 1.5, 2, "F");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(65, 75, 90);

    y = addWrappedText(
      item,
      margin + 8,
      y,
      pageWidth - margin * 2 - 8,
      6,
      10
    );

    y += 3;
  });

  // Missing keywords
  y += 7;

  if (y > pageHeight - 75) {
    addFooter(2);
    doc.addPage();
    addHeader("Resume Insights");
    y = 45;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(45, 55, 72);
  doc.text("03  Missing Keywords", margin, y);

  y += 10;

  const keywords = analysis.missingKeywords || [];

  if (keywords.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(90, 100, 115);
    doc.text("No major missing keywords were identified.", margin, y);
  } else {
    let keywordX = margin;
    let keywordY = y;

    keywords.forEach((keyword) => {
      const width =
        doc.getTextWidth(String(keyword)) + 12;

      if (keywordX + width > pageWidth - margin) {
        keywordX = margin;
        keywordY += 12;
      }

      doc.setFillColor(238, 242, 255);
      doc.roundedRect(
        keywordX,
        keywordY - 7,
        width,
        9,
        2,
        2,
        "F"
      );

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(55, 65, 100);
      doc.text(String(keyword), keywordX + 6, keywordY - 1);

      keywordX += width + 5;
    });

    y = keywordY + 15;
  }

  addFooter(2);

  // =========================================================
  // PAGE 3 — AI RECOMMENDATIONS
  // =========================================================

  doc.addPage();
  addHeader("AI Recommendations");

  let suggestionY = 47;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 110, 125);

  suggestionY = addWrappedText(
    "Based on the resume analysis, here are the key improvements recommended by ResumeIQ:",
    margin,
    suggestionY,
    pageWidth - margin * 2,
    6,
    10
  );

  suggestionY += 10;

  const suggestions = analysis.suggestions || [];

  suggestions.forEach((suggestion, index) => {
    if (suggestionY > pageHeight - 45) {
      addFooter(3);
      doc.addPage();
      addHeader("AI Recommendations");
      suggestionY = 47;
    }

    // Number box
    doc.setFillColor(45, 55, 72);
    doc.roundedRect(
      margin,
      suggestionY - 6,
      10,
      10,
      2,
      2,
      "F"
    );

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);

    doc.text(
      String(index + 1),
      margin + 5,
      suggestionY + 1,
      { align: "center" }
    );

    // Suggestion text
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(65, 75, 90);

    suggestionY = addWrappedText(
      suggestion,
      margin + 16,
      suggestionY,
      pageWidth - margin * 2 - 16,
      6,
      10
    );

    suggestionY += 9;
  });

  // Final summary box
  if (suggestionY > pageHeight - 75) {
    addFooter(3);
    doc.addPage();
    addHeader("AI Recommendations");
    suggestionY = 47;
  }

  suggestionY += 5;

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(
    margin,
    suggestionY,
    pageWidth - margin * 2,
    45,
    5,
    5,
    "F"
  );

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(45, 55, 72);
  doc.text("Next Step", margin + 10, suggestionY + 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(90, 100, 115);

  addWrappedText(
    "Apply the recommendations above, update your resume, and analyze the revised version again to measure your improvement.",
    margin + 10,
    suggestionY + 25,
    pageWidth - margin * 2 - 20,
    5,
    9
  );

  addFooter(3);

  // ---------- Save ----------
  doc.save("ResumeIQ-Analysis-Report.pdf");
};

